<?php

/** @var \Magento\Catalog\Block\Product\View\Description $block */

$_product = $block->getProduct();
?>
<div data-bind="scope: 'startSimple'">
    <h2 data-bind="text: titleFromKo"></h2>
    <!-- ko template: getTemplate() --><!-- /ko -->
    <h2 data-bind="text: clock"></h2>
</div>


<script type="text/x-magento-init">

{
    "*": {
        "Magento_Ui/js/core/app": {
            "components": {
                "startSimple": {
                   "component": "Elogic_SimpleKoModule/js/koScript",
                   "titleMessage": "<?= __('Hello m2') ?>",
                   "productNameFromPhtml": "<?= $_product->getName() ?>"
                }
            }
        }
    }
}
</script>
